Repository NVIDIA/NVFlare, pull requests merged in 2021-12, with the labels that each got.

#55 Fixed the sys_info client error
  nvflare/private/fed/server/sys_cmd.py
Labels: bug

#56 Fix #52 streaming errors
  nvflare/apis/analytix.py
  nvflare/app_common/widgets/streaming.py
  test/test_analytix.py
  test/test_streaming.py
Labels: bug

#64 Update docs with key features, polish and fix more docs build errors
  docs/examples/hello_cross_val.rst
  docs/examples/hello_numpy.rst
  docs/examples/hello_pt.rst
  docs/examples/hello_tf2.rst
  docs/faq.rst
  docs/highlights.rst
  docs/index.rst
  docs/programming_guide.rst
  docs/programming_guide/best_practices.rst
  docs/programming_guide/controllers.rst
  docs/programming_guide/controllers/cross_site_model_evaluation.rst
  docs/programming_guide/controllers/cyclic_workflow.rst
  docs/programming_guide/controllers/scatter_and_gather_workflow.rst
  docs/programming_guide/filters.rst
  docs/quickstart.rst
  docs/user_guide.rst
  docs/user_guide/application.rst
  docs/user_guide/workspace.rst
  nvflare/apis/app_validation.py
  nvflare/apis/controller_spec.py
  nvflare/apis/dxo.py
  nvflare/apis/impl/controller.py
Labels: documentation

#57 Add log critical to FLComponent and update docstrings
  nvflare/apis/event_type.py
  nvflare/apis/fl_component.py
  nvflare/widgets/info_collector.py
Labels: core

#45 some minor updates to cifar10 example
  examples/cifar10/README.md
  examples/cifar10/figs/plot_tensorboard_events.py
  examples/cifar10/pt/trainers/cifar10_trainer.py
  examples/cifar10/run_fl.py
  examples/cifar10/run_poc.sh
Labels: examples

#71 add example README files
  examples/README.md
  examples/hello-cyclic/README.md
  examples/hello-monai/README.md
  examples/hello-numpy-cross-val/README.md
  examples/hello-numpy-sag/README.md
  examples/hello-pt/README.md
  examples/hello-tf2/README.md
Labels: examples
