Repository NVIDIA/NVFlare, pull requests merged in 2022-05, with the labels that each got.

#464 Update cifar10 data setup procedure in integration tests apps
  runtest.sh
  tests/integration_test/apps/pt/config/config_fed_client.json
  tests/integration_test/apps/pt/custom/cifar10trainer.py
  tests/integration_test/apps/pt/custom/cifar10validator.py
  tests/integration_test/system_test.py
  tests/integration_test/test_internal.yml
Labels: cicd

#507 Modify existing premerge CI to runs-on temp-ci label
  .github/workflows/premerge.yml
Labels: cicd

#508 Modify existing premerge CI to runs-on temp-ci label
  .github/workflows/premerge.yml
Labels: cicd

#513 Add hello examples into CI integration tests
  CODEOWNERS
  tests/integration_test/admin_controller.py
  tests/integration_test/data/apps/cross_val/config/config_fed_client.json
  tests/integration_test/data/apps/cross_val/config/config_fed_server.json
  tests/integration_test/data/apps/cross_val_one_client/config/config_fed_client.json
  tests/integration_test/data/apps/cross_val_one_client/config/config_fed_server.json
  tests/integration_test/data/apps/filters/config/config_fed_client.json
  tests/integration_test/data/apps/filters/config/config_fed_server.json
  tests/integration_test/data/apps/global_model_eval/config/config_fed_client.json
  tests/integration_test/data/apps/global_model_eval/config/config_fed_server.json
  tests/integration_test/data/apps/sag/config/config_fed_client.json
  tests/integration_test/data/apps/sag/config/config_fed_server.json
  tests/integration_test/data/apps/sag_exception/config/config_fed_server.json
  tests/integration_test/data/apps/sag_exception/custom/np_trainer.py
  tests/integration_test/data/apps/sag_weights_diff/config/config_fed_server.json
  tests/integration_test/data/apps/sag_weights_diff/custom/constants.py
  tests/integration_test/data/apps/sag_weights_diff/custom/np_trainer.py
  tests/integration_test/data/apps/tb_streaming/config/config_fed_server.json
  tests/integration_test/data/test_examples.yml
  tests/integration_test/np/__init__.py
  tests/integration_test/np/constants.py
  tests/integration_test/np/np_formatter.py
  tests/integration_test/np/np_model_locator.py
  tests/integration_test/np/np_model_persistor.py
  tests/integration_test/np/np_trainer.py
  tests/integration_test/np/np_validator.py
  tests/integration_test/system_test.py
  tests/integration_test/utils.py
Labels: cicd

#517 Init blossom-ci workflow
  .github/workflows/blossom-ci.yml
Labels: cicd

#519 Init blossom-ci workflow
  .github/workflows/blossom-ci.yml
Labels: cicd

#515 Fix event recorder
  nvflare/app_common/widgets/event_recorder.py
Labels: bug

#514 Fix np codes
  nvflare/app_common/np/np_formatter.py
  nvflare/app_common/np/np_model_locator.py
  nvflare/app_common/np/np_model_persistor.py
  nvflare/app_common/np/np_trainer.py
  nvflare/app_common/np/np_validator.py
Labels: bug

#516 Clean up CI integration tests
  tests/README.md
  tests/integration_test/README.md
  tests/integration_test/data/apps/tb_streaming/custom/custom_controller.py
  tests/integration_test/data/single_app_as_job/test_example_apps.yml
  tests/integration_test/data/single_app_as_job/test_ha.yml
  tests/integration_test/data/single_app_as_job/test_internal_apps.yml
  tests/integration_test/data/system/1_server_2_clients.yml
  tests/integration_test/data/system/ha_1_server_2_clients.yml
  tests/integration_test/system_test.py
  tests/integration_test/test_cases.yml
Labels: cicd

#523 Blossom test
  setup.py
Labels: cicd

#550 cifar-10: update poc multi-task instructions
  examples/cifar10/README.md
Labels: examples

#552 Update HE exception message
  nvflare/app_common/homomorphic_encryption/he_model_encryptor.py
Labels: enhancement

#531 Change tmp path under tmp/nvflare
  nvflare/lighter/project.yml
  nvflare/poc/server/startup/fed_server.json
  nvflare/poc/server/startup/fed_server_HA.json
  tests/integration_test/data/system/1_server_2_clients.yml
  tests/integration_test/data/system/ha_1_server_2_clients.yml
Labels: enhancement

#556 Remove minio server in test scripts and fix format issues
  requirements-dev.txt
  runtest.sh
  tests/unit_test/app_common/storages/storage_test.py
  tests/unit_test/lighter/project_test.py
  tests/unit_test/private/fed/server/fed_server_test.py
  tests/unit_test/private/fed/server/job_validator_test.py
Labels: cicd

#565 logout from admin api after submitting job
  examples/cifar10/submit_job.py
  examples/prostate/prostate_2D/submit_job.py
  examples/prostate/prostate_3D/submit_job.py
Labels: examples

#569 remove study store in cifar10 example project
  examples/cifar10/workspaces/secure_project.yml
Labels: examples

#561 Update hello-pt and hello-pt-tb example
  examples/hello-pt-tb/config/config_fed_server.json
  examples/hello-pt-tb/custom/pt_constants.py
  examples/hello-pt-tb/custom/pt_learner.py
  examples/hello-pt-tb/custom/simple_network.py
  examples/hello-pt/config/config_fed_server.json
  examples/hello-pt/custom/cifar10trainer.py
  examples/hello-pt/custom/cifar10validator.py
  examples/hello-pt/custom/pt_constants.py
  examples/hello-pt/custom/pt_model_locator.py
  examples/hello-pt/custom/simple_network.py
  examples/hello-pt/custom/validation_json_generator.py
  tests/integration_test/data/apps/pt/config/config_fed_server.json
  tests/integration_test/data/apps/pt/custom/cifar10trainer.py
  tests/integration_test/data/apps/pt/custom/cifar10validator.py
  tests/integration_test/data/apps/pt/custom/pt_model_locator.py
  tests/integration_test/data/apps/pt/custom/simple_network.py
  tests/integration_test/data/single_app_as_job/test_example_apps.yml
Labels: examples

#589 Fix snapshot persistor with storage
  nvflare/apis/fl_snapshot.py
  nvflare/apis/state_persistor.py
  nvflare/app_common/state_persistors/storage_state_persistor.py
  nvflare/app_common/storages/filesystem_storage.py
  nvflare/lighter/project.yml
  nvflare/poc/server/startup/fed_server.json
  nvflare/poc/server/startup/fed_server_HA.json
  tests/integration_test/admin_controller.py
  tests/integration_test/data/ha/kill_server_after_training_complete.yml
  tests/integration_test/data/ha/kill_server_during_training_after_first_round.yml
  tests/integration_test/data/ha/kill_server_during_training_before_first_round.yml
  tests/integration_test/data/ha/kill_server_during_training_sending_model.yml
  tests/integration_test/site_launcher.py
  tests/integration_test/test_fladminapi.py
  tests/unit_test/app_common/storages/storage_test.py
Labels: bug, cicd

#527 Init pre-merge scripts
  ci/run_premerge_cpu.sh
  ci/run_premerge_gpu.sh
Labels: cicd

#617 cifar-10: don't set cuda visible devices
  examples/cifar10/start_fl_secure.sh
Labels: examples
