Repository NVIDIA/NVFlare, pull requests merged in 2022-03, with the labels that each got.

#227 Re-structure test app validators and yml file
  test/app_testing/admin_controller.py
  test/app_testing/app_result_validator.py
  test/app_testing/run_app_tests.sh
  test/app_testing/run_example_tests.sh
  test/app_testing/site_launcher.py
  test/app_testing/test_apps/test_examples.yml
  test/app_testing/test_apps/test_simple.yml
  test/app_testing/test_examples.yml
  test/app_testing/test_simple.yml
  test/app_testing/validators/cross_val_result_validator.py
  test/app_testing/validators/cross_val_single_client_validator.py
  test/app_testing/validators/filters_result_validator.py
  test/app_testing/validators/global_model_eval_validator.py
  test/app_testing/validators/pt_model_validator.py
  test/app_testing/validators/sag_result_validator.py
  test/app_testing/validators/tb_result_validator.py
  test/app_testing/validators/tf_model_validator.py
Labels: cicd

#244 Quit admin after timeout dev
  nvflare/fuel/hci/client/api.py
  nvflare/fuel/hci/client/api_status.py
  nvflare/fuel/hci/client/cli.py
  nvflare/fuel/hci/client/fl_admin_api.py
  nvflare/fuel/hci/server/login.py
  nvflare/fuel/hci/server/sess.py
  nvflare/private/fed/server/admin.py
Labels: enhancement

#224 Minor updates to documentation
  docs/examples/hello_pt.rst
  docs/faq.rst
  docs/programming_guide/controllers.rst
  docs/resources/Controller_worker.png
Labels: documentation

#237 Re-organize unit tests
  test/test_jsonscaner.py
  test/unit_test/__init__.py
  test/unit_test/apis/test_analytix.py
  test/unit_test/apis/test_fl_context.py
  test/unit_test/apis/test_format_check.py
  test/unit_test/app_common/test_accumulate_weighted_aggregator.py
  test/unit_test/app_common/test_exclude_vars.py
  test/unit_test/app_common/test_in_time_accumulate_weighted_aggregator.py
  test/unit_test/app_common/test_in_time_model_selection_handler.py
  test/unit_test/app_common/test_streaming.py
  test/unit_test/controller/__init__.py
  test/unit_test/controller/controller_test.py
  test/unit_test/controller/test_basic.py
  test/unit_test/controller/test_broadcast_behavior.py
  test/unit_test/controller/test_callback.py
  test/unit_test/controller/test_invalid_input.py
  test/unit_test/controller/test_relay_behavior.py
  test/unit_test/controller/test_send_bahavior.py
  test/unit_test/controller/test_task.py
  test/unit_test/controller/test_task_mgmt.py
  test/unit_test/fuel/test_json_scanner.py
  test/unit_test/fuel/test_security_utils.py
  test/unit_test/private/test_messageproto.py
  test/unit_test/utils.py
Labels: cicd

#260 Update cifar10 plotting script
  examples/cifar10/figs/plot_tensorboard_events.py
Labels: examples

#250 Fix server startup path propogation
  nvflare/private/fed/app/server/server_train.py
Labels: bug

#287 Fix license issue
  nvflare/ha/overseer/worker.py
  runtest.sh
Labels: cicd

#292 Bugfix HE aggregator
  nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py
Labels: bug

#295 Fix #258 by adding 3 measures against DoS attacks
  nvflare/fuel/hci/conn.py
  nvflare/fuel/hci/server/hci.py
Labels: core

#297 Fix isort issue
  nvflare/fuel/hci/server/hci.py
Labels: cicd

#296 Fix isort/black/flake8 issues
  nvflare/apis/fl_component.py
  nvflare/apis/fl_constant.py
  nvflare/apis/fl_snapshot.py
  nvflare/apis/overseer_spec.py
  nvflare/apis/persistable.py
  nvflare/apis/state_persistor.py
  nvflare/app_common/abstract/model_persistor.py
  nvflare/app_common/state_persistors/snapshot_file_persistor.py
  nvflare/app_common/state_persistors/storage_state_persistor.py
  nvflare/app_common/storages/filesystem_storage.py
  nvflare/app_common/workflows/scatter_and_gather.py
  nvflare/fuel/hci/client/cli.py
  nvflare/fuel/hci/tools/admin.py
  nvflare/ha/dummy_overseer_agent.py
  nvflare/ha/overseer/overseer.py
  nvflare/ha/overseer/utils.py
  nvflare/ha/overseer_agent_gui.py
  nvflare/lighter/impl/static_file.py
  nvflare/private/fed/app/client/worker_process.py
  nvflare/private/fed/app/fl_conf.py
  nvflare/private/fed/app/trainers/server_deployer.py
  nvflare/private/fed/client/base_client_deployer.py
  nvflare/private/fed/client/client_engine.py
  nvflare/private/fed/client/communicator.py
  nvflare/private/fed/client/fed_client.py
  nvflare/private/fed/client/fed_client_base.py
  nvflare/private/fed/server/fed_server.py
  nvflare/private/fed/server/server_engine.py
  nvflare/private/fed/server/server_runner.py
  nvflare/private/fed/server/server_state.py
  test/app_testing/admin_controller.py
  test/app_testing/np/np_trainer.py
  test/app_testing/np/np_validator.py
  test/app_testing/run_app_tests.sh
  test/app_testing/run_example_tests.sh
  test/app_testing/site_launcher.py
  test/app_testing/test_apps/tb_streaming/custom/custom_executor.py
  test/app_testing/test_runner.py
Labels: enhancement, cicd

#254 make task name configurable
  examples/federated_analysis/configs/fed_analysis/config/config_fed_client.json
  examples/federated_analysis/configs/fed_analysis/config/config_fed_server.json
  examples/federated_analysis/configs/fed_analysis/custom/analysis_constants.py
  examples/federated_analysis/configs/fed_analysis/custom/analysis_controller.py
  examples/federated_analysis/configs/fed_analysis/custom/analysis_executor.py
Labels: examples

#313 Documentation: Add information about the usage of name vs path
  docs/user_guide/application.rst
Labels: documentation

#314 Fixes #301 by lowering max admin connections to 16.
  nvflare/fuel/hci/server/hci.py
Labels: core

#326 support data kind WEIGHTS in HE
  nvflare/app_common/homomorphic_encryption/he_model_decryptor.py
  nvflare/app_common/homomorphic_encryption/he_model_shareable_generator.py
Labels: bug, examples

#309 Re-organise widgets and handlers
  nvflare/app_common/handlers/__init__.py
  nvflare/app_common/widgets/event_recorder.py
  nvflare/app_common/widgets/intime_model_selector.py
  nvflare/app_common/widgets/streaming.py
  nvflare/widgets/fed_event.py
  test/app_testing/test_apps/pt/config/config_fed_server.json
  test/app_testing/test_apps/pt/custom/validation_json_generator.py
  test/app_testing/test_apps/tb_streaming/config/config_fed_client.json
  test/app_testing/test_apps/tb_streaming/config/config_fed_server.json
  test/unit_test/app_common/test_in_time_model_selector.py
Labels: enhancement

#324 Fix log exception bug
  nvflare/private/event.py
  nvflare/widgets/fed_event.py
Labels: bug

#329 Fix FLComponent docstring typo
  nvflare/apis/fl_component.py
Labels: enhancement

#327 disable byoc in provisioning
  examples/cifar10/workspaces/secure_project.yml
Labels: examples

#286 Clean up codes in nvflare/private/fed/app
  nvflare/private/defs.py
  nvflare/private/fed/app/client/client_train.py
  nvflare/private/fed/app/deployer/base_client_deployer.py
  nvflare/private/fed/app/deployer/server_deployer.py
  nvflare/private/fed/app/fl_conf.py
  nvflare/private/fed/app/server/server_train.py
  nvflare/private/fed/app/trainers/__init__.py
Labels: enhancement

#348 343 fixes svt_privacy
  nvflare/app_common/filters/svt_privacy.py
Labels: bug

#349 343 fixes svt_privacy (#348)
  nvflare/app_common/filters/svt_privacy.py
Labels: bug
