Repository NVIDIA/NVFlare, pull requests merged in 2022-06, with the labels that each got.

#633 fed_analysis: support new dataset with added masks
  examples/federated_analysis/data/prepare_data.py
Labels: examples

#640 Fix unit test run number issue
  tests/integration_test/validators/__init__.py
  tests/unit_test/app_common/aggregators/accumulate_weighted_aggregator_test.py
  tests/unit_test/app_common/aggregators/in_time_accumulate_weighted_aggregator_test.py
  tests/unit_test/app_common/widgets/in_time_model_selector_test.py
Labels: cicd

#644 Update job meta validator test
  tests/unit_test/data/deployment/invalid/all_other.json
  tests/unit_test/data/deployment/invalid/dup_all.json
  tests/unit_test/data/deployment/invalid/dup_client.json
  tests/unit_test/data/deployment/invalid/dup_server.json
  tests/unit_test/data/deployment/invalid/empty_dict.json
  tests/unit_test/data/deployment/invalid/no_deployment.json
  tests/unit_test/data/deployment/invalid/no_deployment_2.json
  tests/unit_test/data/deployment/valid/all.json
  tests/unit_test/data/deployment/valid/all_idle.json
  tests/unit_test/data/deployment/valid/idle_app.json
  tests/unit_test/data/deployment/valid/one_app.json
  tests/unit_test/data/deployment/valid/two_apps.json
  tests/unit_test/data/jobs/valid_app_as_job/config/config_fed_client.json
  tests/unit_test/data/jobs/valid_app_as_job/config/config_fed_server.json
  tests/unit_test/data/jobs/valid_job_deployment_all_idle/meta.json
  tests/unit_test/data/jobs/valid_job_deployment_all_idle/sag1/config/config_fed_client.json
  tests/unit_test/data/jobs/valid_job_deployment_all_idle/sag1/config/config_fed_server.json
  tests/unit_test/data/jobs/valid_job_deployment_all_idle/sag2/config/config_fed_client.json
  tests/unit_test/data/jobs/valid_job_deployment_all_idle/sag2/config/config_fed_server.json
  tests/unit_test/private/fed/server/job_meta_validator_test.py
Labels: cicd

#651 Enable per participant component specification
  nvflare/lighter/impl/static_file.py
  nvflare/lighter/project.yml
Labels: enhancement

#666 update cifar-10 project file
  examples/cifar10/workspaces/secure_project.yml
Labels: examples

#669 fed_analysis example: use download_job command; don't specify cuda devices
  examples/federated_analysis/README.md
  examples/federated_analysis/start_fl_poc.sh
Labels: examples

#681 Update example access result part and update documentation
  .gitignore
  docs/example_applications.rst
  docs/examples/access_result.rst
  docs/examples/hello_cross_val.rst
  docs/examples/hello_numpy.rst
  docs/examples/hello_pt.rst
  docs/examples/hello_pt_tb.rst
  docs/examples/hello_scatter_and_gather.rst
  docs/examples/hello_tf2.rst
  docs/examples/run_example.rst
  docs/examples/run_fl_system.rst
  docs/examples/shutdown_fl_system.rst
  docs/quickstart.rst
  docs/user_guide/overview.rst
  examples/federated_analysis/README.md
  examples/federated_analysis/figs/histograms_example.svg
  examples/federated_analysis/histograms_example.html
  examples/hello-numpy-cross-val/config/config_fed_server.json
Labels: documentation, examples

#684 Update workspace related documentation
  docs/examples/access_result.rst
  docs/examples/hello_tf2.rst
  docs/user_guide/application.rst
  docs/user_guide/job.rst
  docs/user_guide/overview.rst
  docs/user_guide/workspace.rst
Labels: documentation

#600 add function to clean and install pip deps
  ci/run_premerge_cpu.sh
  ci/run_premerge_gpu.sh
Labels: cicd

#700 Add dns entries into ci scripts
  ci/run_premerge_gpu.sh
Labels: cicd
