Repository NVIDIA/NVFlare, pull requests merged in 2022-02, with the labels that each got.

#166 added hello-pt-tb example with Learner API and tb streaming
  docs/examples/hello_pt_tb.rst
  docs/quickstart.rst
  examples/hello-pt-tb/README.md
  examples/hello-pt-tb/config/config_fed_client.json
  examples/hello-pt-tb/config/config_fed_server.json
  examples/hello-pt-tb/custom/pt_constants.py
  examples/hello-pt-tb/custom/pt_learner.py
  examples/hello-pt-tb/custom/simple_network.py
  nvflare/app_common/widgets/validation_json_generator.py
Labels: examples

#174 Fix private/fed/server docstrings
  nvflare/private/fed/server/admin.py
  nvflare/private/fed/server/client_manager.py
  nvflare/private/fed/server/cmd_utils.py
  nvflare/private/fed/server/fed_server.py
  nvflare/private/fed/server/info_coll_cmd.py
  nvflare/private/fed/server/result_processor.py
  nvflare/private/fed/server/run_manager.py
  nvflare/private/fed/server/server_aux_runner.py
  nvflare/private/fed/server/server_cmd_modules.py
  nvflare/private/fed/server/server_engine.py
  nvflare/private/fed/server/server_engine_internal_spec.py
  nvflare/private/fed/server/server_json_config.py
  nvflare/private/fed/server/server_runner.py
  nvflare/private/fed/server/shell_cmd.py
  nvflare/private/fed/server/sys_cmd.py
  nvflare/private/fed/server/training_cmds.py
Labels: documentation, enhancement

#176 Improve docstrings and coding style for fuel
  nvflare/fuel/hci/base64_utils.py
  nvflare/fuel/hci/client/api_status.py
  nvflare/fuel/hci/client/fl_admin_api_constants.py
  nvflare/fuel/hci/client/fl_admin_api_runner.py
  nvflare/fuel/hci/client/fl_admin_api_spec.py
  nvflare/fuel/hci/cmd_arg_utils.py
  nvflare/fuel/hci/conn.py
  nvflare/fuel/hci/file_transfer_defs.py
  nvflare/fuel/hci/proto.py
  nvflare/fuel/hci/reg.py
  nvflare/fuel/hci/security.py
  nvflare/fuel/hci/server/audit.py
  nvflare/fuel/hci/server/authz.py
  nvflare/fuel/hci/server/builtin.py
  nvflare/fuel/hci/server/constants.py
  nvflare/fuel/hci/server/file_transfer.py
  nvflare/fuel/hci/server/hci.py
  nvflare/fuel/hci/server/login.py
  nvflare/fuel/hci/server/reg.py
  nvflare/fuel/hci/server/sess.py
  nvflare/fuel/hci/shell_cmd_val.py
  nvflare/fuel/hci/tools/authz_preview.py
  nvflare/fuel/hci/zip_utils.py
  nvflare/fuel/utils/argument_utils.py
  nvflare/fuel/utils/class_utils.py
  nvflare/fuel/utils/comm.py
  nvflare/fuel/utils/component_builder.py
  nvflare/fuel/utils/json_scanner.py
  nvflare/fuel/utils/pipe/file_pipe.py
  nvflare/fuel/utils/pipe/pipe.py
  nvflare/fuel/utils/wfconf.py
Labels: enhancement

#162 Update admin client command line interface to based on AdminAPI
  nvflare/fuel/hci/client/api.py
  nvflare/fuel/hci/client/api_spec.py
  nvflare/fuel/hci/client/cli.py
  nvflare/fuel/hci/client/file_transfer.py
  nvflare/fuel/hci/client/fl_admin_api.py
  nvflare/fuel/hci/server/file_transfer.py
  nvflare/fuel/hci/table.py
  nvflare/fuel/hci/tools/admin.py
  test/app_testing/admin_controller.py
Labels: core

#191 Fix show_stats command
  nvflare/fuel/hci/client/api_spec.py
Labels: bug

#154 Fix all issues of isort/black after including nvflare/private folder
  nvflare/app_common/filters/exclude_vars.py
  nvflare/app_common/filters/percentile_privacy.py
  nvflare/app_common/filters/svt_privacy.py
  nvflare/app_common/handlers/intime_model_selection_handler.py
  nvflare/app_common/pt/pt_file_model_locator.py
  nvflare/fuel/hci/client/cli.py
  runtest.sh
  setup.cfg
Labels: enhancement

#210 Add persistence to admin cli
  nvflare/fuel/hci/client/cli.py
  nvflare/fuel/hci/tools/admin.py
Labels: enhancement

#212 211 Update hello-monai example
  examples/hello-monai/config/config_fed_server.json
  examples/hello-monai/config/config_train.json
  examples/hello-monai/config/dataset_total.json
  examples/hello-monai/custom/monai_trainer.py
  examples/hello-monai/custom/train_configer.py
Labels: examples

#164 Federated analysis example to compute local and global histograms
  3rdParty/itk-io.LICENSE.txt
  3rdParty/kaleido.LICENSE.txt
  3rdParty/monai.LICENSE.txt
  3rdParty/pandas.LICENSE.txt
  3rdParty/plotly.LICENSE.txt
  examples/README.md
  examples/federated_analysis/.gitignore
  examples/federated_analysis/README.md
  examples/federated_analysis/configs/fed_analysis/config/config_fed_client.json
  examples/federated_analysis/configs/fed_analysis/config/config_fed_server.json
  examples/federated_analysis/configs/fed_analysis/custom/analysis_controller.py
  examples/federated_analysis/configs/fed_analysis/custom/analysis_executor.py
  examples/federated_analysis/create_poc_workpace.sh
  examples/federated_analysis/data/prepare_data.py
  examples/federated_analysis/histograms_example.html
  examples/federated_analysis/histograms_example.svg
  examples/federated_analysis/run_fl.py
  examples/federated_analysis/run_poc.sh
  examples/federated_analysis/virtualenv/requirements.txt
  examples/federated_analysis/virtualenv/set_env.sh
  examples/federated_analysis/workspaces/.gitkeep
Labels: examples
