Repository NVIDIA/NVFlare, pull requests merged in 2022-10, with the labels that each got.

#1004 Fix xgboost histogram based issue [skip ci]
  examples/xgboost/histogram-based/job_configs/base/app/custom/higgs_executor.py
  nvflare/app_opt/xgboost/histogram_based/executor.py
Labels: examples

#1005 [CICD] add new members to trigger list of blossom-ci [skip ci]
  .github/workflows/blossom-ci.yml
Labels: cicd

#1009 Make heartbeat_timeout optional
  nvflare/private/fed/app/deployer/server_deployer.py
  nvflare/private/fed/app/deployer/simulator_deployer.py
Labels: enhancement

#1037 Fix shutdown command
  nvflare/private/fed/server/training_cmds.py
Labels: bug

#1058 Updated getting started guide to use FL Simulator [skip ci]
  docs/getting_started.rst
  docs/resources/getting_started_tb-train-loss.png
Labels: documentation

#1071 Fix docstring description [skip ci]
  nvflare/app_common/workflows/cross_site_model_eval.py
Labels: documentation

#1088 Clean up xgboost rst file and move to doc directory [skip ci]
  docs/examples/xgboost.rst
  examples/xgboost/README.md
  examples/xgboost/histogram-based/README.md
  examples/xgboost/tree-based/README.md
  examples/xgboost/utils/prepare_data_split.py
  nvflare/app_opt/xgboost/README.rst
  nvflare/app_opt/xgboost/histogram_based/controller.py
  nvflare/app_opt/xgboost/histogram_based/executor.py
  nvflare/app_opt/xgboost/histogram_based/executor_spec.py
Labels: documentation, examples

#1094 Fix example code format [skip ci]
  examples/brats18/result_stat/plot_tensorboard_events.py
  examples/brats18/result_stat/plot_tensorboard_events_poc.py
  examples/cifar10/cifar10-sim/figs/plot_tensorboard_events.py
  examples/cifar10/cifar10-sim/set_alpha.py
  examples/federated-policies/policies/site_b/custom/test_filter.py
Labels: examples
