Repository NVIDIA/NVFlare, pull requests merged in 2022-09, with the labels that each got.

#718 add CodeQL action
  .github/workflows/codeql.yml
Labels: cicd

#863 added holgerroth to trigger list
  .github/workflows/blossom-ci.yml
Labels: cicd

#910 Use GPU 0 GPUResourceManager as default [gpu]
  ci/run_premerge_cpu.sh
  nvflare/app_common/resource_managers/auto_clean_resource_manager.py
  nvflare/app_common/resource_managers/base_resource_manager.py
  nvflare/app_common/workflows/scatter_and_gather.py
  nvflare/app_common/workflows/scatter_and_gather_scaffold.py
  nvflare/lighter/impl/master_template.yml
  nvflare/poc/client/local/resources.json
  tests/integration_test/run_integration_tests.sh
Labels: enhancement, cicd

#931 add sections for the docs changes needed for 2.2 [skip ci]
  docs/conf.py
  docs/key_features.rst
  docs/programming_guide/filters.rst
  docs/programming_guide/provisioning_system.rst
  docs/real_world_fl.rst
  docs/user_guide.rst
  docs/user_guide/authorization_policy_previewer.rst
  docs/user_guide/dashboard_ui.rst
  docs/user_guide/dynamic_provisioning.rst
  docs/user_guide/federated_authorization.rst
  docs/user_guide/fl_simulator.rst
  docs/user_guide/nvflare_cli.rst
  docs/user_guide/nvflare_security.rst
  docs/user_guide/poc_command.rst
  docs/user_guide/preflight_check.rst
  docs/user_guide/site_policy_management.rst
Labels: documentation

#938 remove hello-monai and update hello-monai-bundle readme [skip ci]
  examples/hello-monai-bundle/README.md
  examples/hello-monai-bundle/app/config/config_fed_client.json
  examples/hello-monai-bundle/app/config/config_fed_server.json
  examples/hello-monai-bundle/app/custom/bundle_configer.py
  examples/hello-monai-bundle/app/custom/monai_trainer.py
  examples/hello-monai-bundle/meta.json
  examples/hello-monai/README.md
  examples/hello-monai/app/config/config_fed_client.json
  examples/hello-monai/app/config/config_fed_server.json
  examples/hello-monai/app/config/config_train.json
  examples/hello-monai/app/config/dataset_part1.json
  examples/hello-monai/app/config/dataset_part2.json
  examples/hello-monai/app/config/dataset_total.json
  examples/hello-monai/app/custom/monai_trainer.py
  examples/hello-monai/app/custom/train_configer.py
  examples/hello-monai/meta.json
Labels: examples

#939 Update hello-* example readme to use simulator [skip ci]
  examples/hello-cyclic/README.md
  examples/hello-numpy-cross-val/README.md
  examples/hello-numpy-sag/README.md
  examples/hello-pt-tb/README.md
  examples/hello-pt/README.md
  examples/hello-tf2/README.md
Labels: documentation, examples

#932 Unit Tests for examples and README update [skip ci]
  examples/federated_statistics/df_stats/README.md
  examples/federated_statistics/df_stats/RUN_TESTS_README.md
  examples/federated_statistics/df_stats/demo/visualization.ipynb
  examples/federated_statistics/df_stats/df_stats_job/custom/tests/df_statistics_test.py
  examples/federated_statistics/df_stats/df_stats_job/custom/tests/simulate_stats_job_test.py
  examples/federated_statistics/image_stats/README.md
  examples/federated_statistics/image_stats/demo/visualization.ipynb
  examples/federated_statistics/image_stats/figs/image_histogram.png
  examples/federated_statistics/image_stats/figs/image_histogram_1.png
  examples/federated_statistics/image_stats/figs/image_histogram_2.png
  examples/federated_statistics/image_stats/image_stats_job/config/config_fed_client.json
  examples/federated_statistics/image_stats/image_stats_job/custom/image_statistics.py
  nvflare/app_opt/statistics/visualization/statistics_visualization.py
Labels: documentation, examples

#923 README.rst for app_opt/xgboost module [skip ci]
  nvflare/app_opt/xgboost/README.rst
Labels: documentation
