Repository NVIDIA/NVFlare, pull requests merged in 2023-10, with the labels that each got.

#2057 Enhance PT Client API examples
  examples/hello-world/ml-to-fl/pt/README.md
  examples/hello-world/ml-to-fl/pt/code/cifar10_fl.py
  examples/hello-world/ml-to-fl/pt/code/cifar10_original.py
  examples/hello-world/ml-to-fl/pt/code/cifar10_structured_original.py
  job_templates/sag_pt/config_fed_server.conf
  job_templates/sag_pt_ddp/app_server/config_fed_server.conf
  job_templates/sag_pt_deploy_map/app_server/config_fed_server.conf
Labels: examples

#2066 Update XGBoost examples
  examples/advanced/vertical_xgboost/README.md
  examples/advanced/vertical_xgboost/code/psi/local_psi.py
  examples/advanced/vertical_xgboost/code/vertical_xgb/vertical_data_loader.py
  examples/advanced/vertical_xgboost/jobs/vertical_xgb/app/config/config_fed_client.json
  examples/advanced/vertical_xgboost/jobs/vertical_xgb/app/config/config_fed_server.json
  examples/advanced/vertical_xgboost/jobs/vertical_xgb/meta.json
  examples/advanced/vertical_xgboost/jobs/vertical_xgb_psi/app/config/config_fed_client.json
  examples/advanced/vertical_xgboost/jobs/vertical_xgb_psi/app/config/config_fed_server.json
  examples/advanced/vertical_xgboost/jobs/vertical_xgb_psi/meta.json
  examples/advanced/vertical_xgboost/requirements.txt
  examples/advanced/xgboost/README.md
  examples/advanced/xgboost/histogram-based/requirements.txt
  job_templates/psi_csv/config_fed_client.conf
  job_templates/psi_csv/config_fed_server.conf
  job_templates/psi_csv/info.conf
  job_templates/psi_csv/info.md
  job_templates/psi_csv/meta.conf
  job_templates/vertical_xgb/config_fed_client.conf
  job_templates/vertical_xgb/config_fed_server.conf
  job_templates/vertical_xgb/info.conf
  job_templates/vertical_xgb/info.md
  job_templates/vertical_xgb/meta.conf
  nvflare/app_opt/xgboost/histogram_based/executor.py
  nvflare/app_opt/xgboost/tree_based/executor.py
Labels: examples

#2070 Client api use exchange task
  nvflare/app_common/abstract/exchange_task.py
  nvflare/app_common/data_exchange/__init__.py
  nvflare/app_common/data_exchange/constants.py
  nvflare/app_common/data_exchange/data_exchanger.py
  nvflare/app_common/data_exchange/file_pipe_data_exchanger.py
  nvflare/app_common/decomposers/common_decomposers.py
  nvflare/app_opt/lightning/api.py
  nvflare/client/__init__.py
  nvflare/client/api.py
  nvflare/client/config.py
  nvflare/client/decorator.py
  nvflare/client/lightning/__init__.py
  nvflare/client/model_registry.py
  nvflare/client/task_registry.py
  nvflare/client/utils.py
  tests/unit_test/app_common/data_exchange/__init__.py
  tests/unit_test/app_common/data_exchange/data_exchanger_test.py
  tests/unit_test/app_common/model_exchange/model_exchanger_test.py
Labels: enhancement

#2060 Fix job cli boolean replacement issue
  nvflare/tool/job/config/config_indexer.py
  nvflare/tool/job/config/configer.py
  tests/unit_test/data/jobs/launch_everytime/app/config/config_fed_client.conf
  tests/unit_test/data/jobs/launch_everytime/app/config/config_fed_server.conf
  tests/unit_test/data/jobs/launch_everytime/meta.conf
  tests/unit_test/data/jobs/launch_once/app/config/config_fed_client.conf
  tests/unit_test/data/jobs/launch_once/app/config/config_fed_server.conf
  tests/unit_test/data/jobs/launch_once/meta.conf
  tests/unit_test/tool/job/config/configer_test.py
Labels: bug

#2089 Support cross site eval in FLModelUtil
  nvflare/apis/fl_constant.py
  nvflare/app_common/utils/fl_model_utils.py
Labels: enhancement

#2087 docs: fix typos [skip ci]
  docs/glossary.rst
  docs/programming_guide/controllers/cross_site_model_evaluation.rst
  docs/real_world_fl/notes_on_large_models.rst
  docs/user_guide/confidential_computing.rst
  docs/user_guide/nvflare_cli/dashboard_command.rst
  docs/user_guide/nvflare_cli/poc_command.rst
Labels: documentation

#2093 Fix cell and core cell
  nvflare/fuel/f3/cellnet/cell.py
  nvflare/fuel/f3/cellnet/core_cell.py
Labels: bug

#2047 Add docs sections and rearrangements [skip ci]
  docs/example_applications_algorithms.rst
  docs/examples/hello_world_examples.rst
  docs/faq.rst
  docs/programming_guide.rst
  docs/programming_guide/serialization.rst
  docs/programming_guide/system_architecture.rst
  docs/real_world_fl.rst
  docs/resources/hub_site.png
  docs/resources/systems_multiple_hierarchies.png
  docs/resources/t2_job_creation.png
  docs/user_guide.rst
  docs/user_guide/authorization_policy_previewer.rst
  docs/user_guide/federated_authorization.rst
  docs/user_guide/hierarchy_unification_bridge.rst
  docs/user_guide/nvflare_cli/fl_simulator.rst
  docs/user_guide/nvflare_security.rst
  docs/user_guide/security/auditing.rst
  docs/user_guide/security/authorization_policy_previewer.rst
  docs/user_guide/security/communication_security.rst
  docs/user_guide/security/data_privacy_protection.rst
  docs/user_guide/security/identity_security.rst
  docs/user_guide/security/serialization.rst
  docs/user_guide/security/site_policy_management.rst
  docs/user_guide/security/terminologies_and_roles.rst
  docs/user_guide/security/unsafe_component_detection.rst
  examples/advanced/README.md
  examples/advanced/job-level-authorization/README.md
  examples/advanced/job-level-authorization/README.rst
  examples/hello-world/README.md
  examples/hello-world/hello-ccwf/README.md
  examples/hello-world/step-by-step/readme.md
Labels: documentation

#2095 Fix job cli create issue
  nvflare/tool/job/config/configer.py
  nvflare/tool/job/job_cli.py
  nvflare/tool/job/job_client_const.py
  tests/unit_test/data/jobs/launch_everytime/meta.conf
  tests/unit_test/tool/job/config/configer_test.py
Labels: bug

#2106 Last notebook example fix
  examples/advanced/federated-statistics/image_stats/jobs/image_stats/app/custom/image_statistics.py
  integration/monai/flare_monai_integration.ipynb
Labels: examples

#2102 Support both int and float
  nvflare/apis/analytix.py
  tests/unit_test/app_common/widgets/streaming_test.py
Labels: enhancement

#2109 Major updates to GNN example
  examples/advanced/gnn-pt/README.md
  examples/advanced/gnn-pt/jobs/gnn-pt/app/config/config_fed_client.json
  examples/advanced/gnn-pt/jobs/gnn-pt/app/config/config_fed_server.json
  examples/advanced/gnn-pt/jobs/gnn-pt/app/custom/graphsage.py
  examples/advanced/gnn-pt/jobs/gnn-pt/meta.json
  examples/advanced/gnn-pt/loss_train_fl.svg
  examples/advanced/gnn-pt/loss_train_graphsage.svg
  examples/advanced/gnn-pt/requirements.txt
  examples/advanced/gnn/README.md
  examples/advanced/gnn/code/graphsage_finance_fl.py
  examples/advanced/gnn/code/graphsage_finance_local.py
  examples/advanced/gnn/code/graphsage_protein_fl.py
  examples/advanced/gnn/code/graphsage_protein_local.py
  examples/advanced/gnn/code/process_elliptic.py
  examples/advanced/gnn/code/pyg_sage.py
  examples/advanced/gnn/figs/finance_train_loss.png
  examples/advanced/gnn/figs/finance_val_auc.png
  examples/advanced/gnn/figs/protein_train_loss.png
  examples/advanced/gnn/figs/protein_val_f1.png
  examples/advanced/gnn/requirements.txt
  job_templates/sag_pt_gnn_supervised/app_1/config_fed_client.conf
  job_templates/sag_pt_gnn_supervised/app_2/config_fed_client.conf
  job_templates/sag_pt_gnn_supervised/app_server/config_fed_server.conf
  job_templates/sag_pt_gnn_supervised/info.conf
  job_templates/sag_pt_gnn_supervised/info.md
  job_templates/sag_pt_gnn_supervised/meta.conf
  job_templates/sag_pt_gnn_unsupervised/app_1/config_fed_client.conf
  job_templates/sag_pt_gnn_unsupervised/app_2/config_fed_client.conf
  job_templates/sag_pt_gnn_unsupervised/app_server/config_fed_server.conf
  job_templates/sag_pt_gnn_unsupervised/info.conf
  job_templates/sag_pt_gnn_unsupervised/info.md
  job_templates/sag_pt_gnn_unsupervised/meta.conf
Labels: documentation, examples

#2111 Add None to is_primitive to support null in conf/json files
  nvflare/tool/job/config/config_indexer.py
  tests/unit_test/tool/job/config/config_indexer_test.py
Labels: bug
