Repository NVIDIA/NVFlare, pull requests merged in 2023-03, with the labels that each got.

#1455 Fix cifar and auto generated integration tests
  examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/cifar10_fedavg_he/config/config_fed_client.json
  examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_stream_tb/cifar10_fedavg_stream_tb/config/config_fed_client.json
  examples/advanced/cifar10/cifar10-real-world/prepare_data.sh
  examples/advanced/cifar10/cifar10-real-world/run_experiments.sh
  examples/advanced/cifar10/cifar10-sim/prepare_data.sh
  examples/advanced/cifar10/cifar10-sim/run_experiments.sh
  examples/advanced/cifar10/pt/utils/cifar10_data_utils.py
  examples/advanced/cifar10/pt/utils/cifar10_download_data.py
  examples/advanced/experiment-tracking/tensorboard-streaming/jobs/tensorboard-streaming/app/custom/pt_learner.py
  examples/advanced/sklearn-kmeans/jobs/sklearn_kmeans_base/app/config/config_fed_client.json
  examples/advanced/sklearn-kmeans/jobs/sklearn_kmeans_base/app/config/config_fed_server.json
  examples/advanced/sklearn-kmeans/prepare_data.sh
  examples/advanced/sklearn-kmeans/run_experiment_simulator.sh
  examples/advanced/sklearn-kmeans/utils/prepare_data.py
  examples/advanced/sklearn-kmeans/utils/prepare_job_config.py
  examples/advanced/sklearn-linear/jobs/sklearn_linear_base/app/config/config_fed_client.json
  examples/advanced/sklearn-linear/jobs/sklearn_linear_base/app/config/config_fed_server.json
  examples/advanced/sklearn-linear/prepare_data.sh
  examples/advanced/sklearn-linear/prepare_job_config.sh
  examples/advanced/sklearn-linear/run_experiment_simulator.sh
  examples/advanced/sklearn-linear/utils/prepare_job_config.py
  examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/config/config_fed_client.json
  examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/config/config_fed_server.json
  examples/advanced/sklearn-svm/prepare_data.sh
  examples/advanced/sklearn-svm/run_experiment_simulator.sh
  examples/advanced/sklearn-svm/utils/prepare_data.py
  examples/advanced/sklearn-svm/utils/prepare_job_config.py
  nvflare/app_opt/he/intime_accumulate_model_aggregator.py
  nvflare/app_opt/sklearn/data_loader.py
  tests/README.md
  tests/integration_test/data/test_configs/standalone_job/cifar_examples.yml
  tests/integration_test/src/utils.py
  tests/test_utils.py
  tests/unit_test/apis/impl/controller_test.py
Labels: examples, cicd

#1466 Fix job runner multiple start issue
  nvflare/private/fed/server/fed_server.py
  nvflare/private/fed/server/job_runner.py
  tests/integration_test/data/test_configs/ha/two_servers.yml
  tests/integration_test/test_configs.yml
Labels: bug

#1475 Get rid of hello-examples warnings
  examples/.gitignore
  examples/hello-world/hello-numpy-cross-val/jobs/hello-numpy-cross-val/app/config/config_fed_server.json
  examples/hello-world/hello-numpy-sag/jobs/hello-numpy-sag/app/config/config_fed_server.json
  examples/hello-world/hello-pt/jobs/hello-pt/app/config/config_fed_server.json
  examples/hello-world/hello-tf2/jobs/hello-tf2/app/config/config_fed_server.json
  nvflare/app_common/np/np_trainer.py
Labels: enhancement, examples

#1478 Update protobuf version
  setup.cfg
Labels: dependencies

#1459 Fix controller timing issue
  nvflare/apis/impl/any_relay_manager.py
  nvflare/apis/impl/controller.py
  nvflare/apis/impl/seq_relay_manager.py
  runtest.sh
  tests/unit_test/apis/impl/controller_test.py
  tests/unit_test/fuel/utils/component_builder_test.py
Labels: bug

#1519 Fix auth test
  runtest.sh
  tests/integration_test/data/apps/slow_job/config/config_fed_client.json
  tests/integration_test/data/apps/slow_job/config/config_fed_server.json
  tests/integration_test/data/apps/slow_job/custom/slow_trainer.py
  tests/integration_test/data/test_configs/authorization/abort_job.yml
  tests/integration_test/data/test_configs/authorization/list_job.yml
  tests/integration_test/src/nvf_test_driver.py
  tests/unit_test/app_common/executors/statistics/mock_df_stats_executor.py
Labels: cicd

#1535 Ha authentication fix
  nvflare/apis/fl_constant.py
  nvflare/private/fed/app/server/runner_process.py
  nvflare/private/fed/app/simulator/simulator_worker.py
  nvflare/private/fed/client/client_run_manager.py
  nvflare/private/fed/client/communicator.py
  nvflare/private/fed/server/fed_server.py
  nvflare/private/fed/server/server_command_agent.py
  nvflare/private/fed/server/server_commands.py
  nvflare/private/fed/server/server_engine.py
  nvflare/private/fed/server/server_state.py
  nvflare/private/fed/simulator/simulator_server.py
  nvflare/private/fed/utils/decomposers/private_decomposers.py
Labels: bug, core

#1549 Fixed the shared object issue in the controller task return.
  nvflare/apis/impl/controller.py
  nvflare/private/fed/server/server_commands.py
  nvflare/private/fed/server/server_runner.py
Labels: bug

#1492 Fix HA integration tests
  tests/integration_test/data/apps/slow_job/config/config_fed_server.json
  tests/integration_test/data/test_configs/ha/kill_one_server_during_training_after_first_round.yml
  tests/integration_test/data/test_configs/ha/kill_one_server_during_training_before_first_round.yml
  tests/integration_test/data/test_configs/ha/kill_server_after_training_complete.yml
  tests/integration_test/data/test_configs/ha/kill_server_during_training_after_first_round.yml
  tests/integration_test/data/test_configs/ha/kill_server_during_training_before_first_round.yml
  tests/integration_test/data/test_configs/ha/kill_server_during_training_sending_model.yml
  tests/integration_test/src/utils.py
Labels: cicd

#1557 Enhance preflight check
  nvflare/tool/package_checker/check_rule.py
  nvflare/tool/package_checker/client_package_checker.py
  nvflare/tool/package_checker/package_checker.py
  nvflare/tool/package_checker/utils.py
  tests/integration_test/preflight_check_test.py
Labels: enhancement

#1562 Fix integration tests issues
  tests/integration_test/data/test_configs/authorization/test_diff_job_config.yml
  tests/integration_test/src/nvf_test_driver.py
  tests/integration_test/src/utils.py
Labels: cicd

#1563 Fix abort job with only connected clients
  nvflare/private/fed/server/job_cmds.py
  nvflare/private/fed/server/job_runner.py
Labels: bug, core

#1572 Fix max client in client_manager
  nvflare/private/fed/server/client_manager.py
Labels: core

#1575 Update fed policy example [skip ci]
  examples/advanced/federated-policies/README.rst
  examples/advanced/federated-policies/setup.sh
Labels: examples

#1593 test client-side model initialization
  tests/integration_test/data/apps/pt_init_client/config/config_fed_client.json
  tests/integration_test/data/apps/pt_init_client/config/config_fed_server.json
  tests/integration_test/data/apps/pt_init_client/custom/cifar10trainer.py
  tests/integration_test/data/apps/pt_init_client/custom/cifar10validator.py
  tests/integration_test/data/apps/pt_init_client/custom/pt_constants.py
  tests/integration_test/data/apps/pt_init_client/custom/pt_model_locator.py
  tests/integration_test/data/apps/pt_init_client/custom/simple_network.py
  tests/integration_test/data/test_configs/standalone_job/internal_pt.yml
Labels: cicd

#1611 Don't submit update with task data from old SSID
  nvflare/apis/fl_constant.py
  nvflare/private/fed/client/communicator.py
Labels: core

#1599 Add docstring to executor [skip ci]
  nvflare/apis/executor.py
Labels: documentation

#1621 Change default initial task fetch interval at client side from 0.1 to 0.5
  nvflare/private/fed/client/client_runner.py
Labels: enhancement

#1612 Add missing parent constructor
  nvflare/private/fed/client/client_app_runner.py
Labels: enhancement
