Repository NVIDIA/NVFlare, pull requests merged in 2023-04, with the labels that each got.

#1619 Do not shutdown job runner when server turn to cold state
  nvflare/apis/fl_constant.py
  nvflare/app_common/job_schedulers/job_scheduler.py
  nvflare/private/fed/server/fed_server.py
  nvflare/private/fed/server/job_runner.py
  nvflare/private/fed/server/server_commands.py
  nvflare/private/fed/server/server_engine.py
  nvflare/private/fed/server/server_runner.py
  tests/unit_test/private/fed/server/fed_server_test.py
Labels: bug, core

#1653 Fix readme typos [skip ci]
  examples/README.md
Labels: documentation

#1659 Improve example readme [skip ci]
  examples/README.md
  examples/advanced/README.md
  examples/advanced/brats18/README.md
  examples/advanced/cifar10/README.md
  examples/advanced/experiment-tracking/README.md
  examples/advanced/federated-statistics/README.md
  examples/advanced/nlp-ner/README.md
  examples/advanced/prostate/README.md
  examples/advanced/psi/README.md
  examples/advanced/random_forest/README.md
  examples/advanced/sklearn-kmeans/README.md
  examples/advanced/sklearn-linear/README.md
  examples/advanced/sklearn-svm/README.md
  examples/advanced/vertical_federated_learning/README.md
  examples/advanced/xgboost/README.md
  examples/hello-world/README.md
  examples/tutorials/README.md
Labels: documentation

#1688 Fix learners in examples
  examples/advanced/sklearn-kmeans/jobs/sklearn_kmeans_base/app/custom/kmeans_learner.py
  examples/advanced/sklearn-linear/jobs/sklearn_linear_base/app/custom/linear_learner.py
  examples/advanced/sklearn-svm/jobs/sklearn_svm_base/app/custom/svm_learner.py
  examples/advanced/vertical_federated_learning/cifar10-splitnn/src/splitnn/cifar10_learner_splitnn.py
Labels: examples

#1689 Change sticky to False for SSID
  nvflare/private/fed/client/communicator.py
Labels: core

#1683 Install all requirements first in auto test config
  tests/integration_test/src/utils.py
Labels: cicd

#1686 Docs fixes main [skip ci]
  docs/real_world_fl/overview.rst
  examples/README.md
Labels: documentation

#1702 Fix SAG docstring
  nvflare/app_common/workflows/scatter_and_gather.py
  nvflare/app_common/workflows/scatter_and_gather_scaffold.py
Labels: documentation

#1707 Fix code format [skip ci]
  research/auto-fed-rl/src/autofedrl/autofedrl_cifar10_learner.py
  research/auto-fed-rl/src/autofedrl/autofedrl_scatter_and_gather.py
  research/auto-fed-rl/src/autofedrl/pt_autofedrl.py
  research/fed-sm/jobs/fedsm_prostate/app/custom/learners/supervised_monai_prostate_fedsm_learner.py
  research/quantifying-data-leakage/jobs/app_template/server/config/config_fed_server.json
  research/quantifying-data-leakage/src/nvflare_gradinv/learners/cxr_learner.py
Labels: research

#1706 Fix minor problems in simulator
  nvflare/private/fed/app/simulator/simulator_runner.py
Labels: enhancement
