Repository NVIDIA/NVFlare, pull requests merged in 2023-02, with the labels that each got.

#1284 Add missing __init__.py
  nvflare/app_opt/sklearn/__init__.py
Labels: enhancement

#1286 Create pull_request_template.md [skip ci]
  .github/pull_request_template.md
Labels: documentation

#1315 Add cifar integration test
  tests/integration_test/data/projects/cifar.yml
  tests/integration_test/data/test_configs/standalone_job/test_cifar.yml
  tests/integration_test/run_integration_tests.sh
  tests/integration_test/src/action_handlers.py
  tests/integration_test/src/fl_test_driver.py
  tests/integration_test/test_configs.yml
  tests/integration_test/validators/__init__.py
  tests/integration_test/validators/cifar10_result_validator.py
Labels: cicd

#1314 Update documentation
  docs/conf.py
  docs/example_applications_algorithms.rst
  docs/examples/hello_cross_val.rst
  docs/examples/hello_pt.rst
  docs/examples/hello_pt_tb.rst
  docs/examples/hello_scatter_and_gather.rst
  docs/examples/hello_tf2.rst
  docs/getting_started.rst
  docs/programming_guide/high_availability.rst
  docs/programming_guide/provisioning_system.rst
  docs/quickstart.rst
  docs/real_world_fl/application.rst
  docs/real_world_fl/flare_api.rst
  docs/real_world_fl/migrating_to_flare_api.rst
  docs/real_world_fl/overview.rst
  docs/resources/Dockerfile.doc
  docs/user_guide/dashboard_ui.rst
  requirements-doc.txt
Labels: documentation

#1303 Increase the wait to ensure the primary sp is updated
  tests/integration_test/overseer_test.py
Labels: cicd

#1347 Add warnings to ModuleScanner
  nvflare/app_common/pt/__init__.py
  nvflare/fuel/utils/class_utils.py
Labels: enhancement

#1358 Fix argument error in model_persistence_format_manager
  nvflare/app_opt/pt/model_persistence_format_manager.py
Labels: bug

#1369 Change warning to debug for ModuleScanner
  nvflare/fuel/utils/class_utils.py
  tests/integration_test/data/apps/pt_use_name/config/config_fed_client.json
  tests/integration_test/data/apps/pt_use_name/config/config_fed_server.json
  tests/integration_test/data/apps/pt_use_name/custom/cifar10trainer.py
  tests/integration_test/data/apps/pt_use_name/custom/cifar10validator.py
  tests/integration_test/data/apps/pt_use_name/custom/pt_constants.py
  tests/integration_test/data/apps/pt_use_name/custom/pt_model_locator.py
  tests/integration_test/data/apps/pt_use_name/custom/simple_network.py
  tests/integration_test/data/apps/pt_use_path/config/config_fed_client.json
  tests/integration_test/data/apps/pt_use_path/config/config_fed_server.json
  tests/integration_test/data/apps/pt_use_path/custom/cifar10trainer.py
  tests/integration_test/data/apps/pt_use_path/custom/cifar10validator.py
  tests/integration_test/data/apps/pt_use_path/custom/pt_constants.py
  tests/integration_test/data/apps/pt_use_path/custom/pt_model_locator.py
  tests/integration_test/data/apps/pt_use_path/custom/simple_network.py
  tests/integration_test/data/test_configs/standalone_job/internal_pt.yml
Labels: enhancement, cicd

#1392 Move HE from app_common to app_opt. Update app_opt requirements
  .github/workflows/premerge.yml
  build_doc.sh
  ci/run_integration.sh
  ci/run_premerge.sh
  docs/contributing.rst
  examples/advanced/tensorboard-streaming/README.md
  examples/advanced/tensorboard-streaming/job_configs/tensorboard-streaming/app/config/config_fed_server.json
  examples/advanced/tensorboard-streaming/requirements.txt
  nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py
  nvflare/app_common/homomorphic_encryption/he_model_decryptor.py
  nvflare/app_common/homomorphic_encryption/he_model_encryptor.py
  nvflare/app_common/homomorphic_encryption/he_model_shareable_generator.py
  nvflare/app_common/homomorphic_encryption/he_pt_model_reader_writer.py
  nvflare/app_common/homomorphic_encryption/homomorphic_encrypt.py
  nvflare/app_common/pt/tb_receiver.py
  nvflare/app_opt/he/__init__.py
  nvflare/app_opt/he/constant.py
  nvflare/app_opt/he/homomorphic_encrypt.py
  nvflare/app_opt/he/intime_accumulate_model_aggregator.py
  nvflare/app_opt/he/model_decryptor.py
  nvflare/app_opt/he/model_encryptor.py
  nvflare/app_opt/he/model_shareable_generator.py
  nvflare/app_opt/pt/__init__.py
  nvflare/app_opt/pt/ditto.py
  nvflare/app_opt/pt/file_model_locator.py
  nvflare/app_opt/pt/file_model_persistor.py
  nvflare/app_opt/pt/he_model_reader_writer.py
  nvflare/app_opt/pt/model_reader_writer.py
  nvflare/app_opt/pt/tb_receiver.py
  nvflare/app_opt/tracking/mlflow/mlflow_receiver.py
  nvflare/app_opt/tracking/tensorboard/__init__.py
  nvflare/fuel/utils/class_utils.py
  requirements-dev.txt
  requirements-doc.txt
  runtest.sh
  setup.cfg
  tests/integration_test/data/apps/tb_streaming/config/config_fed_client.json
  tests/integration_test/data/apps/tb_streaming/config/config_fed_server.json
Labels: enhancement, cicd, dependencies

#1370 Fix integration tests
  ci/run_integration.sh
  nvflare/tool/package_checker/client_package_checker.py
  nvflare/tool/package_checker/nvflare_console_package_checker.py
  nvflare/tool/package_checker/package_checker.py
  nvflare/tool/package_checker/server_package_checker.py
  nvflare/tool/package_checker/utils.py
  nvflare/tool/preflight_check.py
  setup.cfg
  tests/integration_test/data/projects/dummy.yml
  tests/integration_test/preflight_check_test.py
  tests/integration_test/src/utils.py
Labels: cicd

#1427 Fix list jobs command argument parsing bug
  nvflare/fuel/hci/client/fl_admin_api_spec.py
  nvflare/private/fed/server/job_cmds.py
  tests/integration_test/src/action_handlers.py
  tests/integration_test/src/fl_test_driver.py
  tests/integration_test/src/utils.py
  tests/unit_test/private/fed/server/job_cmds_test.py
Labels: bug
