Repository NVIDIA/NVFlare, pull requests merged in 2023-01, with the labels that each got.

#1239 Fix integration tests
  nvflare/app_common/filters/svt_privacy.py
  nvflare/app_common/homomorphic_encryption/he_intime_accumulate_model_aggregator.py
  nvflare/app_common/homomorphic_encryption/he_model_encryptor.py
  nvflare/fuel/hci/client/fl_admin_api.py
  nvflare/private/fed/app/__init__.py
  nvflare/private/fed/app/client/sub_worker_process.py
  nvflare/private/fed/app/client/worker_process.py
  nvflare/private/fed/app/deployer/simulator_deployer.py
  nvflare/private/fed/app/server/__init__.py
  nvflare/private/fed/app/server/server_train.py
  nvflare/private/fed/app/simulator/simulator_runner.py
  nvflare/private/fed/app/simulator/simulator_worker.py
  nvflare/private/fed/app/utils.py
  nvflare/private/fed/server/job_cmds.py
  tests/.gitignore
  tests/integration_test/README.md
  tests/integration_test/src/__init__.py
  tests/integration_test/src/action_handlers.py
  tests/integration_test/src/fl_test_driver.py
  tests/integration_test/src/utils.py
  tests/integration_test/system_test.py
  tests/integration_test/test_configs.yml
  tests/unit_test/apis/analytix_test.py
  tests/unit_test/app_common/executors/statistics/statistics_executor_test.py
  tests/unit_test/app_common/job_schedulers/job_scheduler_test.py
  tests/unit_test/app_common/workflow/mock_common_controller.py
  tests/unit_test/private/fed/app/deployer/simulator_deployer_test.py
  tests/unit_test/private/fed/app/simulator/simulator_runner_test.py
Labels: enhancement, cicd

#1242 remove key check in task get_prop method
  nvflare/apis/controller_spec.py
  tests/unit_test/apis/controller_spec_test.py
Labels: enhancement

#1241 Fix tb streaming
  nvflare/app_common/widgets/streaming.py
  nvflare/app_common/workflows/common_controller.py
  tests/integration_test/data/apps/tb_streaming/custom/custom_controller.py
  tests/integration_test/system_test.py
Labels: bug, cicd

#1243 Update black/isort/flake8 and fix code style [skip ci]
  examples/hello-pt-tb/app/custom/test_custom.py
  examples/hello-pt/app/custom/test_custom.py
  examples/xgboost/utils/baseline_centralized.py
  requirements-dev.txt
Labels: enhancement

#1250 Revert flake8 and isort version
  requirements-dev.txt
Labels: cicd, dependencies

#1246 Drop python 3.7 support
  pyproject.toml
  setup.cfg
  setup.py
Labels: packaging

#1163 Add kmeans clustering example based on scikit-learn
  examples/sklearn-kmeans/README.md
  examples/sklearn-kmeans/data_prepare.sh
  examples/sklearn-kmeans/figs/minibatch.png
  examples/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/config/config_fed_client.json
  examples/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/config/config_fed_server.json
  examples/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/custom/kmeans_assembler.py
  examples/sklearn-kmeans/job_configs/sklearn_kmeans_base/app/custom/kmeans_learner.py
  examples/sklearn-kmeans/job_configs/sklearn_kmeans_base/meta.json
  examples/sklearn-kmeans/prepare_job_config.sh
  examples/sklearn-kmeans/run_experiment_simulator.sh
  examples/sklearn-kmeans/utils/prepare_data.py
  examples/sklearn-kmeans/utils/prepare_job_config.py
  nvflare/app_common/aggregators/assembler.py
  nvflare/app_common/aggregators/collect_and_assemble_aggregator.py
  nvflare/app_common/utils/file_utils.py
  nvflare/app_opt/sklearn/data_loader.py
  nvflare/app_opt/sklearn/joblib_model_param_persistor.py
  nvflare/app_opt/sklearn/sklearn_executor.py
  nvflare/app_opt/sklearn/sklearner.py
Labels: enhancement, examples
