Repository NVIDIA/NVFlare, pull requests merged in 2023-07, with the labels that each got.

#1834 Update fl_component.rst [skip ci]
  docs/programming_guide/fl_component.rst
Labels: documentation

#1833 Update data_exchange_object.rst [skip ci]
  docs/programming_guide/data_exchange_object.rst
Labels: documentation

#1835 Fix bug in RFXGBoost notebook that prevented correct rendering [skip ci]
  examples/advanced/random_forest/random_forest.ipynb
Labels: examples

#1840 Update doc 2.3 [skip ci]
  docs/programming_guide/data_exchange_object.rst
  docs/programming_guide/fl_component.rst
  examples/advanced/random_forest/random_forest.ipynb
Labels: documentation

#1842 Fix auth integration test
  nvflare/private/fed/server/job_meta_validator.py
  tests/integration_test/data/test_configs/authorization/test_diff_job_config.yml
Labels: cicd

#1847 Fix auto integration tests
  examples/advanced/sklearn-svm/README.md
  examples/advanced/sklearn-svm/prepare_job_config.sh
  examples/advanced/sklearn-svm/requirements.txt
  examples/advanced/sklearn-svm/run_experiment_simulator.sh
  nvflare/fuel/utils/config_factory.py
  nvflare/private/fed/app/default_app_validator.py
Labels: examples, cicd

#1845 Add unit tests of SubprocessLauncher and ModelExchanger
  tests/unit_test/app_common/launchers/__init__.py
  tests/unit_test/app_common/launchers/subprocess_launcher_test.py
  tests/unit_test/app_common/model_exchange/__init__.py
  tests/unit_test/app_common/model_exchange/model_exchanger_test.py
Labels: cicd

#1855 Add decorator example
  examples/advanced/ml-to-fl/README.md
  examples/advanced/ml-to-fl/jobs/decorator/app/config/config_exchange.json
  examples/advanced/ml-to-fl/jobs/decorator/app/config/config_fed_client.json
  examples/advanced/ml-to-fl/jobs/decorator/app/config/config_fed_server.json
  examples/advanced/ml-to-fl/jobs/decorator/app/custom/cifar10.py
  examples/advanced/ml-to-fl/jobs/decorator/app/custom/net.py
  examples/advanced/ml-to-fl/jobs/decorator/meta.json
Labels: examples

#1869 Separate plot-requirements out
  examples/advanced/cifar10/cifar10-real-world/README.md
  examples/advanced/cifar10/cifar10-real-world/plot-requirements.txt
  examples/advanced/cifar10/cifar10-real-world/requirements.txt
  examples/advanced/cifar10/cifar10-sim/README.md
  examples/advanced/cifar10/cifar10-sim/plot-requirements.txt
  examples/advanced/cifar10/cifar10-sim/requirements.txt
  examples/advanced/xgboost/tree-based/README.md
  examples/advanced/xgboost/tree-based/plot-requirements.txt
  examples/advanced/xgboost/tree-based/requirements.txt
Labels: examples

#1883 Fix examples and FLModel
  examples/hello-world/ml-to-fl/jobs/client_api1/app/custom/cifar10.py
  examples/hello-world/ml-to-fl/jobs/client_api2/app/custom/cifar10.py
  examples/hello-world/ml-to-fl/jobs/decorator/app/custom/cifar10.py
  nvflare/app_common/abstract/fl_model.py
  nvflare/client/lightning/__init__.py
Labels: enhancement, examples

#1884 Fix integration test
  tests/integration_test/src/nvf_test_driver.py
Labels: cicd
