Repository NVIDIA/NVFlare, pull requests merged in 2024-03, with the labels that each got.

#2384 [2.4] Fix NEMO links
  .github/workflows/markdown-links-check.yml
  .github/workflows/mlc_config.json
  integration/nemo/examples/README.md
  integration/nemo/examples/peft/README.md
  integration/nemo/examples/prompt_learning/README.md
  integration/nemo/examples/prompt_learning/prompt_learning_20B.md
  integration/nemo/examples/supervised_fine_tuning/README.md
Labels: documentation, cicd

#2385 Fix NEMO links
  .github/workflows/markdown-links-check.yml
  .github/workflows/mlc_config.json
  integration/nemo/examples/README.md
  integration/nemo/examples/peft/README.md
  integration/nemo/examples/prompt_learning/README.md
  integration/nemo/examples/prompt_learning/prompt_learning_20B.md
  integration/nemo/examples/supervised_fine_tuning/README.md
Labels: documentation, cicd

#2386 [2.4] Update license headers
  examples/advanced/keycloak-site-authentication/site/local/custom/keycloak_security_handler.py
  examples/hello-world/hello-numpy-cross-val/jobs/hello-numpy-cross-val-only-list-models/pre_train_models.py
  examples/hello-world/hello-numpy-cross-val/jobs/hello-numpy-cross-val-only/pre_train_models.py
  integration/nemo/examples/peft/nemo_nvflare/__init__.py
  integration/nemo/examples/peft/nemo_nvflare/megatron_gpt_peft_tuning.py
  integration/nemo/examples/peft/nemo_nvflare/peft_model.py
  integration/nemo/examples/peft/nemo_nvflare/utils.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/__init__.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/config_sharer.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/constants.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/fed_megatron_gpt_prompt_learning_model.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/learner_executor.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/prompt_encoder.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/prompt_learner.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/share_config.py
  integration/nemo/examples/prompt_learning/nemo_nvflare/utils.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/__init__.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/config_sharer_sft.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/constants.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/learner_executor.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/server_sft_model.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/sft_learner.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/share_config_sft.py
  integration/nemo/examples/supervised_fine_tuning/nemo_nvflare/utils_sft.py
  nvflare/fuel/utils/fobs/lobs.py
  nvflare/lighter/tool_consts.py
  nvflare/tool/poc/service_constants.py
  runtest.sh
  tests/integration_test/data/apps/cyclic/app/custom/__init__.py
  tests/integration_test/data/apps/cyclic/app/custom/tf2_model_persistor.py
  tests/integration_test/data/apps/cyclic/app/custom/tf2_net.py
  tests/integration_test/data/apps/cyclic/app/custom/trainer.py
  tests/integration_test/data/apps/np_sag_weights_diff/app/custom/__init__.py
  tests/integration_test/data/apps/np_sag_weights_diff/app/custom/np_trainer.py
  tests/integration_test/data/apps/sag_exception/app/custom/__init__.py
  tests/integration_test/data/apps/sag_exception/app/custom/exception_trainer.py
  tests/integration_test/data/apps/tb_streaming/app/custom/__init__.py
  tests/integration_test/data/apps/tb_streaming/app/custom/custom_controller.py
  tests/integration_test/data/apps/tb_streaming/app/custom/custom_executor.py
  tests/unit_test/fuel/utils/fobs/datum_test.py
Labels: cicd

#2393 Job submission with binary protocol
  nvflare/apis/impl/job_def_manager.py
  nvflare/apis/job_def.py
  nvflare/apis/job_def_manager_spec.py
  nvflare/apis/storage.py
  nvflare/app_common/storages/filesystem_storage.py
  nvflare/fuel/hci/binary_proto.py
  nvflare/fuel/hci/client/api.py
  nvflare/fuel/hci/client/api_spec.py
  nvflare/fuel/hci/client/file_transfer.py
  nvflare/fuel/hci/conn.py
  nvflare/fuel/hci/file_transfer_defs.py
  nvflare/fuel/hci/proto.py
  nvflare/fuel/hci/server/binary_transfer.py
  nvflare/fuel/hci/server/hci.py
  nvflare/private/fed/server/job_cmds.py
  nvflare/private/fed/server/job_meta_validator.py
  tests/unit_test/apis/impl/job_def_manager_test.py
  tests/unit_test/fuel/hci/binary_proto_test.py
Labels: enhancement

#2446 [2.4] Update fed xgboost docstrings/readme based on stable version
  examples/advanced/vertical_xgboost/README.md
  examples/advanced/vertical_xgboost/requirements.txt
  examples/advanced/xgboost/README.md
  examples/advanced/xgboost/histogram-based/README.md
  examples/advanced/xgboost/histogram-based/requirements.txt
  examples/advanced/xgboost/tree-based/README.md
  examples/advanced/xgboost/tree-based/requirements.txt
  nvflare/app_opt/xgboost/histogram_based/executor.py
  nvflare/app_opt/xgboost/histogram_based_v2/executor.py
  nvflare/app_opt/xgboost/histogram_based_v2/runners/client_runner.py
Labels: documentation

#2415 [2.4] metric relay starts pipe handler heartbeat send/check after task is pulled
  nvflare/app_common/widgets/metric_relay.py
Labels: enhancement

#2442 [2.4] task_exchanger starts pipe handler heartbeat send/check after task is pull
  nvflare/app_common/executors/task_exchanger.py
Labels: enhancement

#2437 [2.4] Use full path for DhPSITaskHandler
  examples/advanced/psi/user_email_match/README.md
  examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_client.conf
  examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_server.conf
  job_templates/psi_csv/config_fed_client.conf
  job_templates/psi_csv/config_fed_server.conf
Labels: bug, examples

#2448 [2.4] Update finance example using job templates
  examples/advanced/finance/jobs/2_histogram/app_server/config/config_fed_server.json
  examples/advanced/finance/jobs/2_histogram/app_site-1/config/config_fed_client.json
  examples/advanced/finance/jobs/2_histogram/app_site-2/config/config_fed_client.json
  examples/advanced/finance/jobs/vertical_xgb/app/config/config_fed_client.json
  examples/advanced/finance/jobs/vertical_xgb/app/config/config_fed_server.json
  examples/advanced/finance/jobs/vertical_xgb/app/custom/vertical_data_loader.py
  examples/advanced/finance/jobs/vertical_xgb/meta.json
  examples/advanced/finance/jobs/vertical_xgb_psi/app/config/config_fed_client.json
  examples/advanced/finance/jobs/vertical_xgb_psi/app/config/config_fed_server.json
  examples/advanced/finance/jobs/vertical_xgb_psi/app/custom/local_psi.py
  examples/advanced/finance/jobs/vertical_xgb_psi/meta.json
  examples/advanced/finance/requirements.txt
  examples/advanced/finance/run_training.sh
  job_templates/vertical_xgb/config_fed_client.conf
  job_templates/vertical_xgb/config_fed_server.conf
Labels: examples

#2450 [2.4] Update github actions
  .github/workflows/blossom-ci.yml
  .github/workflows/codeql.yml
  .github/workflows/markdown-links-check.yml
  .github/workflows/premerge.yml
Labels: cicd
