Repository NVIDIA/NVFlare, pull requests merged in 2024-04, with the labels that each got.

#2433 [2.4] Enhance launcher executor
  nvflare/app_common/executors/client_api_launcher_executor.py
  nvflare/app_common/executors/launcher_executor.py
Labels: enhancement

#2457 [2.4] Remove cancel_futures args
  nvflare/apis/utils/reliable_message.py
Labels: bug

#2458 [2.4] Fix sub_worker_process shutdown
  nvflare/private/fed/app/client/sub_worker_process.py
Labels: bug

#2413 [2.4] Fire and forget for pipe handler control messages
  nvflare/fuel/utils/pipe/file_pipe.py
  nvflare/fuel/utils/pipe/pipe_handler.py
Labels: bug

#2507 [2.3] Fix 2.3 unit tests
  nvflare/fuel/f3/drivers/aio_grpc_driver.py
Labels: cicd

#2502 [2.4] Rely on launcher check_run_status to pause/resume heartbeat
  nvflare/app_common/executors/launcher_executor.py
  nvflare/app_common/executors/task_exchanger.py
Labels: bug

#2517 Use full path for PSI components
  examples/advanced/psi/user_email_match/README.md
  examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_client.conf
  examples/advanced/psi/user_email_match/jobs/user_email_match/app/config/config_fed_server.conf
  job_templates/psi_csv/config_fed_client.conf
  job_templates/psi_csv/config_fed_server.conf
Labels: examples

#2518 Multiple bug fixes from 2.4
  nvflare/apis/utils/reliable_message.py
  nvflare/fuel/f3/drivers/aio_grpc_driver.py
  nvflare/fuel/f3/drivers/grpc_driver.py
  nvflare/private/fed/app/client/sub_worker_process.py
  nvflare/private/fed/app/simulator/simulator_worker.py
Labels: bug

#2519 Enhancements from 2.4
  nvflare/app_common/executors/client_api_launcher_executor.py
  nvflare/app_common/executors/launcher_executor.py
  nvflare/app_common/executors/task_exchanger.py
  nvflare/app_common/widgets/metric_relay.py
  nvflare/fuel/f3/cellnet/cell.py
  nvflare/fuel/utils/pipe/cell_pipe.py
  nvflare/fuel/utils/pipe/file_pipe.py
  nvflare/fuel/utils/pipe/pipe.py
  nvflare/fuel/utils/pipe/pipe_handler.py
Labels: enhancement
