Repository NVIDIA/NVFlare, pull requests merged in 2024-08, with the labels that each got.

#2724 Update MONAI example
  integration/monai/examples/spleen_ct_segmentation_local/README.md
Labels: documentation

#2737 Update getting_started.rst
  docs/getting_started.rst
Labels: documentation

#2752 Minor fix for instructions in setup_poc.ipynb for main
  examples/tutorials/setup_poc.ipynb
Labels: documentation

#2759 Cherry pick XGB docs from #2671
  docs/programming_guide/experiment_tracking.rst
  docs/programming_guide/experiment_tracking/experiment_tracking_apis.rst
  docs/programming_guide/experiment_tracking/experiment_tracking_log_writer.rst
  docs/resources/experiment_tracking_diagram.png
  docs/resources/processor_interface_design.png
  docs/resources/secure_horizontal_xgb.png
  docs/resources/secure_vertical_xgb.png
  docs/resources/xgb_communicator.jpg
  docs/user_guide/federated_xgboost.rst
  docs/user_guide/federated_xgboost/reliable_xgboost_design.rst
  docs/user_guide/federated_xgboost/reliable_xgboost_timeout.rst
  docs/user_guide/federated_xgboost/secure_xgboost_design.rst
  docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
Labels: documentation

#2750 Update xgboost user guide
  docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
Labels: documentation

#2772 Fix config file name in doc
  docs/examples/fl_experiment_tracking_mlflow.rst
Labels: documentation

#2718 Add FedJobAPI documentation
  docs/getting_started.rst
  docs/programming_guide.rst
  docs/programming_guide/execution_api_type.rst
  docs/programming_guide/execution_api_type/client_api.rst
  docs/programming_guide/fed_job_api.rst
  docs/publications_and_talks.rst
  docs/real_world_fl/cloud_deployment.rst
  docs/resources/Dockerfile
  nvflare/job_config/fed_job.py
  tests/unit_test/job_config/fed_job_test.py
Labels: documentation

#2788 Add docstring to reliable message
  nvflare/apis/utils/reliable_message.py
Labels: documentation

#2794 Update xgboost example and ci
  examples/advanced/xgboost/histogram-based/jobs/base_v2/app/config/config_fed_server.json
  examples/advanced/xgboost/utils/prepare_job_config.py
  tests/integration_test/data/test_configs/standalone_job/xgb_histogram_examples.yml
  tests/integration_test/data/test_configs/standalone_job/xgb_tree_examples.yml
Labels: examples, cicd

#2802 Fix HE docstring typo
  nvflare/app_opt/he/homomorphic_encrypt.py
Labels: documentation

#2813 Update xgboost example
  examples/advanced/xgboost_secure/README.md
  examples/advanced/xgboost_secure/prepare_flare_job.sh
  examples/advanced/xgboost_secure/run_training_flare.sh
  examples/advanced/xgboost_secure/train_standalone/train_federated.py
  job_templates/xgboost/config_fed_server.conf
Labels: examples

#2812 Fix Jenkins CI
  examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/cifar10_fedavg_he/config/config_fed_server.json
  tests/integration_test/data/apps/pt_use_name/app/config/config_fed_client.json
  tests/integration_test/data/apps/pt_use_name/app/config/config_fed_server.json
  tests/integration_test/data/apps/pt_use_name/app/custom/cifar10trainer.py
  tests/integration_test/data/apps/pt_use_name/app/custom/cifar10validator.py
  tests/integration_test/data/apps/pt_use_name/app/custom/pt_constants.py
  tests/integration_test/data/apps/pt_use_name/app/custom/pt_model_locator.py
  tests/integration_test/data/apps/pt_use_name/meta.json
  tests/integration_test/data/apps/pt_use_path/app/config/config_fed_server.json
  tests/integration_test/data/apps/tb_streaming/app/config/config_fed_client.json
  tests/integration_test/data/apps/tb_streaming/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-cyclic/app/config/config_fed_client.json
  tests/integration_test/data/jobs/hello-cyclic/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-cyclic/app/custom/__init__.py
  tests/integration_test/data/jobs/hello-cyclic/app/custom/tf2_model_persistor.py
  tests/integration_test/data/jobs/hello-cyclic/app/custom/tf2_net.py
  tests/integration_test/data/jobs/hello-cyclic/app/custom/trainer.py
  tests/integration_test/data/jobs/hello-cyclic/meta.json
  tests/integration_test/data/jobs/hello-numpy-cross-val/app/config/config_fed_client.json
  tests/integration_test/data/jobs/hello-numpy-cross-val/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-numpy-cross-val/meta.json
  tests/integration_test/data/jobs/hello-numpy-sag/app/config/config_fed_client.json
  tests/integration_test/data/jobs/hello-numpy-sag/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-numpy-sag/meta.json
  tests/integration_test/data/jobs/hello-pt/app/config/config_fed_client.json
  tests/integration_test/data/jobs/hello-pt/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-pt/app/custom/cifar10trainer.py
  tests/integration_test/data/jobs/hello-pt/app/custom/cifar10validator.py
  tests/integration_test/data/jobs/hello-pt/app/custom/pt_constants.py
  tests/integration_test/data/jobs/hello-pt/app/custom/pt_model_locator.py
  tests/integration_test/data/jobs/hello-pt/app/custom/simple_network.py
  tests/integration_test/data/jobs/hello-pt/app/custom/test_custom.py
  tests/integration_test/data/jobs/hello-pt/meta.json
  tests/integration_test/data/jobs/hello-tf2/app/config/config_fed_client.json
  tests/integration_test/data/jobs/hello-tf2/app/config/config_fed_server.json
  tests/integration_test/data/jobs/hello-tf2/app/custom/__init__.py
  tests/integration_test/data/jobs/hello-tf2/app/custom/filter.py
  tests/integration_test/data/jobs/hello-tf2/app/custom/tf2_model_persistor.py
  tests/integration_test/data/jobs/hello-tf2/app/custom/tf2_net.py
  tests/integration_test/data/jobs/hello-tf2/app/custom/trainer.py
  tests/integration_test/data/jobs/hello-tf2/meta.json
  tests/integration_test/data/test_configs/ha/two_servers.yml
  tests/integration_test/data/test_configs/standalone_job/hello_ccwf_examples.yml
  tests/integration_test/data/test_configs/standalone_job/np_app.yml
  tests/integration_test/data/test_configs/standalone_job/np_job.yml
  tests/integration_test/data/test_configs/standalone_job/previous_jobs/hello-pt/app/custom/simple_network.py
  tests/integration_test/data/test_configs/standalone_job/pt_app.yml
  tests/integration_test/data/test_configs/standalone_job/pt_job.yml
  tests/integration_test/data/test_configs/standalone_job/tf_app.yml
  tests/integration_test/data/test_configs/standalone_job/tf_job.yml
  tests/integration_test/test_configs.yml
Labels: cicd

#2818 Fix config typos
  examples/advanced/cifar10/cifar10-real-world/jobs/cifar10_fedavg_he/cifar10_fedavg_he/config/config_fed_client.json
  examples/advanced/cifar10/cifar10-sim/jobs/cifar10_central/cifar10_central/config/config_fed_server.json
  examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedavg/cifar10_fedavg/config/config_fed_server.json
  examples/advanced/cifar10/cifar10-sim/jobs/cifar10_fedprox/cifar10_fedprox/config/config_fed_server.json
  examples/advanced/experiment-tracking/tensorboard/jobs/tensorboard-streaming/app/config/config_fed_client.json
Labels: examples

#2860 [2.4] Update controller to use xgb new syntax
  nvflare/app_opt/xgboost/histogram_based/controller.py
Labels: bug

#2888 Add printing of tb logdir
  nvflare/app_opt/tracking/tb/tb_receiver.py
Labels: enhancement

#2890 Added instructions to run horizontal secure XGBoost in simulator
  docs/user_guide/federated_xgboost/secure_xgboost_user_guide.rst
Labels: documentation
