Repository NVIDIA/NVFlare, pull requests merged in 2024-09, with the labels that each got.

#2905 Fix hello-pt-cse job
  tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py
Labels: cicd

#2906 Fixed Plugin README
  integration/xgboost/encryption_plugins/README.md
Labels: documentation

#2917 Fix data save path
  tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py
  tests/integration_test/data/test_configs/standalone_job/pt_job.yml
Labels: cicd

#2927 Fix ci path
  tests/integration_test/data/jobs/hello-pt-cse/app/custom/train.py
  tests/integration_test/data/test_configs/standalone_job/pt_job.yml
Labels: cicd

#2924 Fix xgb standalone fed
  examples/advanced/xgboost_secure/train_standalone/train_federated.py
Labels: examples

#2949 [2.5] Add check before api send 25
  nvflare/client/api.py
  nvflare/client/api_spec.py
  nvflare/client/ex_process/api.py
  nvflare/client/in_process/api.py
  nvflare/client/model_registry.py
  nvflare/client/task_registry.py
Labels: documentation

#2967 [2.5] Fix simulator result path
  examples/advanced/xgboost/histogram-based/xgboost_histogram_higgs.ipynb
  examples/advanced/xgboost/tree-based/utils/plot_tensorboard_events.py
Labels: examples
